# Generated by Django 5.1.15 on 2026-08-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.CharField(
                choices=[
                    ("work", "Work"),
                    ("personal", "Personal"),
                    ("groceries", "Groceries"),
                    ("errands", "Errands"),
                    ("study", "Study"),
                    ("health", "Health"),
                    ("finance", "Finance"),
                    ("home", "Home"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="due_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
    ]
