# Generated by Django 5.1.15 on 2026-08-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_alter_task_category_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ai_model",
            field=models.CharField(default="gemini-3.5-flash", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="auto_approve_proposals",
            field=models.BooleanField(default=False),
        ),
    ]
